{% set name = "oic" %}
{% set version = "0.14.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b276b7072c6817680b54925e3a664d036415a00a524b6847a6bfe55f3135059f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - alabaster
    - beaker
    - future
    - mako
    - pycryptodomex
    - pyjwkest >=1.3.6
    - pyopenssl
    - python
    - requests
    - six

test:
  imports:
    - oic
    - oic.extension
    - oic.oauth2
    - oic.oic
    - oic.utils
    - oic.utils.authn
    - oic.utils.rp
    - oic.utils.userinfo

about:
  home: https://github.com/OpenIDC/pyoidc/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Python implementation of OAuth2 and OpenID Connect

extra:
  recipe-maintainers:
    - mariusvniekerk
