{% set name = "oic" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2de3b83f1299dda8ed0460baad8bb2d4c6ac8bfc08a220c768b7e6e754caf9e7

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  entry_points:
    - oic-client-management = oic.utils.client_management:run

requirements:
  host:
    - pip
    - python >=3.7,<4
  run:
    - requests
    - pycryptodomex
    - pydantic
    - pyjwkest >=1.3.6
    - python >=3.7,<4
    - mako
    - cryptography
    - defusedxml
    - typing_extensions
  run_constrained:
    - python-ldap

test:
  imports:
    - oic
    - oic.extension
    - oic.oauth2
    - oic.oic
    - oic.utils
    - oic.utils.authn
    - oic.utils.rp
    - oic.utils.userinfo

outputs:
  - name: oic

  - name: oic_ldap_authn
    requirements:
      host:
        - python
      run:
        - python
        - python-ldap
        - {{ pin_subpackage('oic', exact=True) }}
    test:
      imports:
        - oic_ldap_authn

about:
  home: https://github.com/OpenIDC/pyoidc/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Python implementation of OAuth2 and OpenID Connect

extra:
  recipe-maintainers:
    - wagnerpeer
    - mariusvniekerk
