{% set name = "oic" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 385a1f64bb59519df1e23840530921bf416740240f505ea6d161e331d3d39fad

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  entry_points:
    - oic-client-management = oic.utils.client_management:run

requirements:
  host:
    - pip
    - python
  run:
    - requests
    - pycryptodomex
    - pydantic-settings
    - pyjwkest >=1.3.6
    - mako
    - cryptography
    - defusedxml
    - typing-extensions
    - python
  run_constrained:
    - cherrypy ==3.2.4  # develop
    - pyopenssl  # develop
    - responses  # tests
    - testfixtures  # tests
    - pytest  # tests
    - freezegun  # tests
    - sphinx  # docs
    - sphinx-autobuild  # docs
    - alabaster  # docs
    - autodoc-pydantic >=2.0.0  # docs
    - pylama  # quality
    - isort  # quality
    - eradicate  # quality
    - mypy  # quality
    - black  # quality
    - bandit  # quality
    - readme_renderer  # quality
    - python-ldap  # ldap-authn
    - beaker  # examples


test:
  imports:
    - oic
    - oic.oauth2
    - oic.oic
    - oic.utils
    - oic.utils.authn
    - oic.utils.userinfo
    - oic.utils.rp
    - oic.extension

about:
  home: https://github.com/OpenIDC/pyoidc/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Python implementation of OAuth2 and OpenID Connect

extra:
  recipe-maintainers:
    - wagnerpeer
    - mariusvniekerk
